# Builda a imagem da aplicação e envia para o Docker Hub
name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v3

      - name: 🔐 Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: 🛠️ Build da imagem do ms-produto do App Lanchonete
        run: |
          docker build \
          --build-arg MODE=prod \
          --build-arg PROFILE=prod \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/fiap-tech-challenge-lanchonete-ms-produto:latest \
          -f Dockerfile .

      - name: 🚀 Push da imagem do ms-produto do App Lanchonete
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fiap-tech-challenge-lanchonete-ms-produto:latest
